<?php require VIEWS_PATH. '/includes/header.phtml'; ?>
    <div class="box-top">
        <div class="container">
            <h1>Cadastro</h1>
        </div>
    </div>
    <div class="container tagname">
        <div class="container">
            <ol class="breadcrumb">
                <li><a href="#">Home</a></li>
                <li><a href="#">Library</a></li>
                <li class="active">Data</li>
            </ol>
        </div>
    </div>
    <div class="container">
        <div class="col-md-12">
            <form method="post" action="<?=HOME?>/students/new">
                <div class="form-group">
                    <label for="full_name">* Nome Completo:</label>
                    <input type="text" class="form-control" id="full_name" name="full_name" placeholder="Digite o Nome completo" required>
                </div>

                <div class="form-group">
                    <label for="cpf">* CPF:</label>
                    <input type="number" class="form-control" id="cpf" name="cpf" placeholder="Digite o CPF, Sem pontos ou traços" required>
                    *Digite o CPF sem pontos ou traços.
                </div>

                <div class="form-group">
                    <label for="email">* Email:</label>
                    <input type="email" class="form-control" id="email" name="email" placeholder="Digite o Email" required>
                </div>

                <div class="form-group">
                    <label for="password">* Senha:</label>
                    <input type="password" class="form-control" id="password" name="password" placeholder="Digite a senha">
                </div>

                <button type="submit" class="btn btn-success">Enviar Contato</button>

                * Campos Obrigatórios.

            </form>
        </div>
    </div>
<?php require VIEWS_PATH. '/includes/footer.phtml';?>